### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by JLuc** [patricekaratchentzeff/Scribus#1]
Hello,
i wanted to try the script, but launching it produces this error :
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "<string>", line 768, in <module>
  File "<string>", line 754, in main_wrapper
  File "<string>", line 668, in main
  File "<string>", line 465, in welcome_banner
NameError: name 'ICON_INFORMATION' is not defined
```

With Scribus 1.5.8 du 23 Janvier 2022, C--T-F-C1.15.10-64bit, on Ubuntu 22.04 with Python 3.10

**Comment by patricekaratchentzeff** [comment]
Hi JLuc,

Thanks for contributing.

I can't reproduce your action. I installed an Ubuntu 22.04 in VM. I got my script and my default test case (test-typo.sla). I used the default Scribus (1.5.8 of 23 janvier 2022) and the default python installation (3.10.6)

When I run the script, it is OK for me (except that the test-typo.sla has an non-existent colorimetric profile, but it doesn't care for the problem).

Can you produce a step-by-step test case for me?

Thanks,

**Comment by patricekaratchentzeff** [comment]
OK : I succeeded by running the script directly from the script entry and not by the console. I confirm the problem.

I catch an eye.

Thanks

**Comment by patricekaratchentzeff** [comment]
OK, it is now updated with the fixed version.

Thank you for report.
